### ISSUE TITLE
np.matrix class removal

### ISSUE THREAD

**Issue by anewt225** [learn-co-curriculum/dsc-lineq-numpy-codealong#1]
Documentation recommends using np.array instead of the np.matrix syntax (Under header: Solve a system of equations with matrix algebra) https://numpy.org/doc/stable/reference/generated/numpy.matrix.html

**Comment by jessepisel** [comment]
Thanks for opening this issue @anewt225 :wave:. I have replaced the `np.matrix()` class with `np.array()` in commit ccbd2ff89f9dd70a7cccbbaba2852f2a57ebefd5.

I am closing this issue at this time.
